import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/header";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = (props) => {
  const { status, data } = useSession();

  return (
    <>
      <Head>
        <title>Curriculo Show</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto">
        <Header />
        <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4"></main>
      </div>
    </>
  );
};

export default Home;
