import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = (props) => {
  // const hello = trpc.useQuery(["pdf"]);
  const { status, data } = useSession();
  console.log({ status, data });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto">
        <header className="w-full h-24 flex items-center justify-between">
          <nav className="flex items-baseline space-x-4">
            <Link href="/">
              <a className="font-extrabold text-2xl text-gray-800">
                Curriculo Show
              </a>
            </Link>
            <Link href="#templates">
              <a className="font-medium text-lg text-gray-600 hover:bg-sky-100 hover:text-sky-600 px-2 py-1 rounded-lg transition duration-75">
                Templates
              </a>
            </Link>
            <Link href="#price">
              <a className="font-medium text-lg text-gray-600 hover:bg-sky-100 hover:text-sky-600 px-2 py-1 rounded-lg transition duration-75">
                Preços
              </a>
            </Link>
          </nav>
          <section className="space-x-4">
            <Link href="/login">
              <a className="font-medium text-lg text-sky-500 hover:text-sky-600 hover:underline hover:decoration-sky-600 px-2 py-1 rounded transition duration-75">
                Login
              </a>
            </Link>
            <Link href="/signup">
              <a className="font-medium text-lg text-white bg-sky-500 hover:bg-sky-600 px-3 py-2 rounded transition duration-75">
                Criar conta
              </a>
            </Link>
          </section>
        </header>
        <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4"></main>
      </div>
    </>
  );
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer">
        Documentation
      </a>
    </section>
  );
};

export default Home;
